### ISSUE TITLE
Link to blog post is not working

### ISSUE THREAD

**Issue by lpsuerj** [aws-samples/data-masking-fine-grained-access-using-aws-lake-formation#2]
The link to the AWS blog post describing the step-by-step process to use the solution does not work and in order to support customer adoption it's important for us to fix it. Can you please update the link referenced in this section: 

> Deployment
Please refer to this [blog post](https://github.com/aws-samples/data-masking-fine-grained-access-using-aws-lake-formation/blob/main) for the detailed instructions on how to use the solution.

**Comment by paragao-cloud** [comment]
Done! Link is working now.
